[build]
  command = "gatsby build"
  publish = "public"

[context.production.environment]
  NODE_VERSION = "16"  # or your preferred version
  GATSBY_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
